name: playground
description: 'FlutterEngineering.io'
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  async: ^2.11.0
  ffi: ^2.1.0
  http: ^1.1.2
  flutter:
    sdk: flutter
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  json_annotation: ^4.8.1
  path_provider: ^2.1.1
  connectivity_plus: ^5.0.2
  flutter_shaders: ^0.1.2
  mockito: ^5.4.4
  encrypt: ^5.0.3
  flutter_secure_storage: ^9.0.0
  cryptography: ^2.7.0
  provider: ^6.1.1
  flutter_riverpod: ^2.4.9
  flutter_bloc: ^8.1.3
  go_router: ^13.2.2
  route_annotations:
    path: ./packages/route_annotations

dev_dependencies:
  flutter_test:
    sdk: flutter
  route_generator:
    path: ./packages/route_generator
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_lints: ^2.0.0
  ffigen: ^10.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  mocktail: ^1.0.2

ffigen:
  output: 'lib/FFIgen/hello_world_bindings.dart'
  headers:
    entry-points:
      - 'lib/FFIgen/hello_world.h'

flutter:
  shaders:
    - shaders/simple.frag
    - shaders/structure.glsl
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
